-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Profiles table: Stores persistent user education details
-- Note: 'users' table might already exist from previous step, but we want a dedicated profile linked to auth
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  university text,
  degree text, -- e.g. B.Tech, BS, WA
  major text, -- e.g. Computer Science
  current_semester integer,
  graduation_year integer,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- Study Plans: Support multiple plans (e.g. per semester)
create table if not exists public.study_plans (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users on delete cascade not null,
  title text not null, -- e.g. "Semester 4 Fall 2025"
  goal text, -- What do they want to achieve?
  start_date date,
  end_date date,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Subjects: The actual courses in a plan
create table if not exists public.subjects (
  id uuid default uuid_generate_v4() primary key,
  plan_id uuid references public.study_plans on delete cascade not null,
  name text not null, -- e.g. "Artificial Intelligence"
  topics text, -- Comma separated topics or description
  status text default 'Not Started', -- Not Started, In Progress, Completed
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Tasks/Checklist: Specific to-dos for a subject (e.g. "Read Chapter 1")
create table if not exists public.tasks (
  id uuid default uuid_generate_v4() primary key,
  subject_id uuid references public.subjects on delete cascade not null,
  description text not null,
  reference text,
  is_completed boolean default false,
  due_date date,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- AI Resources: Links and study materials generated by LLM
create table if not exists public.ai_resources (
  id uuid default uuid_generate_v4() primary key,
  subject_id uuid references public.subjects on delete cascade not null,
  title text,
  url text,
  resource_type text, -- 'video', 'article', 'course'
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Set up Row Level Security (RLS)
-- (Optional but recommended: secure tables so users only see their own data)
alter table public.profiles enable row level security;
alter table public.study_plans enable row level security;
alter table public.subjects enable row level security;
alter table public.tasks enable row level security;
alter table public.ai_resources enable row level security;

-- Simple policies (users can do everything to their own data)
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on profiles for insert with check (auth.uid() = id);

create policy "Users can manage plans" on study_plans for all using (auth.uid() = user_id);
create policy "Users can manage subjects" on subjects for all using (auth.uid() = (select user_id from study_plans where id = subjects.plan_id));
create policy "Users can manage tasks" on tasks for all using (auth.uid() = (select user_id from study_plans sp join subjects s on sp.id = s.plan_id where s.id = tasks.subject_id));
create policy "Users can manage resources" on ai_resources for all using (auth.uid() = (select user_id from study_plans sp join subjects s on sp.id = s.plan_id where s.id = ai_resources.subject_id));
